services:
  mysql-db:
    image: mysql:8.0
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    volumes:
      - db-data:/ssys_ems
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT

  app:
    depends_on:
      - mysql-db
    restart: on-failure
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysql-db:3306/ssys_ems?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.datasource.initialization-mode" : "always",
        "server.port" : "8000",
        "ssys.http.auth.tokenName" : "AUTH_API_KEY",
        "ssys.http.auth.tokenValue" : "ssys" }'
      DATABASE_ROOT_PASSWORD: root
      DATABASE_NAME: ssys_ems
      DATABASE_PORT: 3306

volumes:
  db-data: